"""initial_schema

Revision ID: c1a5639ce6ba
Revises: 
Create Date: 2026-09-28 18:09:44.063044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a5639ce6ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.CheckConstraint('latitude >= -90.0 AND latitude <= 90.0', name='chk_location_latitude'),
    sa.CheckConstraint('longitude >= -180.0 AND longitude <= 180.0', name='chk_location_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('idx_locations_lat_lon', ['latitude', 'longitude'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('system_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('subsystem', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index('idx_system_events_created', ['created_at'], unique=False)
        batch_op.create_index('idx_system_events_severity', ['severity'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_detections_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_vehicles_last_seen', ['last_seen_at'], unique=False)
        batch_op.create_index('idx_vehicles_plate', ['plate_number'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rtsp_url', sa.String(length=500), nullable=False),
    sa.Column('stream_type', sa.String(length=20), nullable=False),
    sa.Column('direction_heading', sa.Integer(), nullable=True),
    sa.Column('fps_target', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index('idx_cameras_location', ['location_id'], unique=False)
        batch_op.create_index('idx_cameras_status', ['status'], unique=False)
        batch_op.create_index('idx_cameras_stream_type', ['stream_type'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_badge_number'), ['badge_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action', ['action', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_logs_time', ['timestamp'], unique=False)
        batch_op.create_index('idx_audit_logs_user', ['user_id', 'timestamp'], unique=False)

    op.create_table('camera_health',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_reachable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('fps_measured', sa.Float(), nullable=True),
    sa.Column('dropped_frames_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_health', schema=None) as batch_op:
        batch_op.create_index('idx_camera_health_cam_time', ['camera_id', 'recorded_at'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('confidence_vehicle', sa.Float(), nullable=False),
    sa.Column('confidence_plate', sa.Float(), nullable=True),
    sa.Column('bbox_vehicle', sa.JSON(), nullable=False),
    sa.Column('bbox_plate', sa.JSON(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=500), nullable=False),
    sa.Column('plate_crop_path', sa.String(length=500), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index('idx_detections_cam_time', ['camera_id', 'detected_at'], unique=False)
        batch_op.create_index('idx_detections_detected_at', ['detected_at'], unique=False)
        batch_op.create_index('idx_detections_plate_time', ['plate_number', 'detected_at'], unique=False)
        batch_op.create_index('idx_detections_vehicle_id', ['vehicle_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_plate', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lead_detective_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_detective_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('idx_investigations_case', ['case_number'], unique=False)
        batch_op.create_index('idx_investigations_plate', ['target_plate'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index('idx_watchlists_active', ['is_active'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('generated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('idx_evidence_inv', ['investigation_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('detection_id_start', sa.Uuid(), nullable=False),
    sa.Column('detection_id_end', sa.Uuid(), nullable=False),
    sa.Column('track_tracker_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('estimated_speed_kmh', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_id_end'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_id_start'], ['detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index('idx_tracks_camera', ['camera_id'], unique=False)

    op.create_table('watchlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_make_model', sa.String(length=100), nullable=True),
    sa.Column('fir_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'plate_number', name='uq_watchlist_entry_plate')
    )
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.create_index('idx_watchlist_entries_plate_active', ['plate_number', 'is_active'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_entry_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['watchlist_entry_id'], ['watchlist_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_camera', ['camera_id'], unique=False)
        batch_op.create_index('idx_alerts_plate', ['plate_number'], unique=False)
        batch_op.create_index('idx_alerts_status_created', ['status', 'created_at'], unique=False)

    op.create_table('investigation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_events', schema=None) as batch_op:
        batch_op.create_index('idx_inv_events_timeline', ['investigation_id', 'sequence_order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigation_events', schema=None) as batch_op:
        batch_op.drop_index('idx_inv_events_timeline')

    op.drop_table('investigation_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_status_created')
        batch_op.drop_index('idx_alerts_plate')
        batch_op.drop_index('idx_alerts_camera')

    op.drop_table('alerts')
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_watchlist_entries_plate_active')

    op.drop_table('watchlist_entries')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('idx_tracks_camera')

    op.drop_table('tracks')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('idx_evidence_inv')

    op.drop_table('evidence')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index('idx_watchlists_active')

    op.drop_table('watchlists')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index('idx_investigations_plate')
        batch_op.drop_index('idx_investigations_case')

    op.drop_table('investigations')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index('idx_detections_vehicle_id')
        batch_op.drop_index('idx_detections_plate_time')
        batch_op.drop_index('idx_detections_detected_at')
        batch_op.drop_index('idx_detections_cam_time')

    op.drop_table('detections')
    with op.batch_alter_table('camera_health', schema=None) as batch_op:
        batch_op.drop_index('idx_camera_health_cam_time')

    op.drop_table('camera_health')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user')
        batch_op.drop_index('idx_audit_logs_time')
        batch_op.drop_index('idx_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_badge_number'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index('idx_cameras_stream_type')
        batch_op.drop_index('idx_cameras_status')
        batch_op.drop_index('idx_cameras_location')

    op.drop_table('cameras')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('idx_vehicles_plate')
        batch_op.drop_index('idx_vehicles_last_seen')

    op.drop_table('vehicles')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index('idx_system_events_severity')
        batch_op.drop_index('idx_system_events_created')

    op.drop_table('system_events')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('idx_locations_lat_lon')

    op.drop_table('locations')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
